import type { Metadata } from "next";
import { Geist, Geist_Mono, Radley } from "next/font/google";
import Nav from "@/app/ui/nav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const radley = Radley({
  weight: "400",
  variable: "--font-radley-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CMB Exteriors",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${radley.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <Nav />
      </body>
    </html>
  );
}
